language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
script:
- source ./environment_test.sh
- py.test --cov decision tests/ --cov-report=term --cov-report=html
after_success:
- coveralls
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: XKyKKo1W62sS/8H5Tse617hdvvodt8Enxt3j/mhhutrsNjf1+Kj6asgsZ5RBqSKKQjenJXG27HQuw3zQL23rHkvaejl0NEZJD4zQKbOYrK0QHQ5oEMf13B/LZhj+odWMvcevcd3EciDihSpLDFPr0meUW+thrKaJFC9NNQxNw3k=
  strategy: git
  app: lr-decision
  on:
    repo: LandRegistry/decision
    branch: master
